apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 155417090997.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 232562f755fb3d8238e59a4f3f19929b578ecc15
